const fs=require('node:fs'),path=require('node:path');
const {chromium}=require(path.join(process.env.PLAYWRIGHT_ROOT,'node_modules/playwright'));
const publication=JSON.parse(fs.readFileSync('realism/publication.json','utf8')),url=publication.url;
if(!url.startsWith('https://rawcdn.githack.com/kokoom94-ai/jeju-now-981/'))throw Error('Unexpected publication origin');
const checks=[],errors=[],failedRequests=[];fs.mkdirSync('realism-qa',{recursive:true});
const state=p=>p.evaluate('window.__JEJU_DEBUG__.state'),visual=p=>p.evaluate('window.__JEJU_REALISM__.status');
const check=(name,ok,details)=>{checks.push({name,passed:!!ok,...(details!==undefined?{details}:{})});if(!ok)throw Error(name);};
async function ready(p){await p.waitForFunction('window.__JEJU_REALISM__?.status.frames>3 && window.__JEJU_REALISM__.status.photoTexturesLoaded===6',null,{timeout:90000});}
async function open(browser,mobile=false){const c=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},isMobile:mobile,hasTouch:mobile,deviceScaleFactor:1});const p=await c.newPage();p.setDefaultTimeout(20000);p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text().slice(0,800));});p.on('requestfailed',r=>failedRequests.push({url:r.url(),error:r.failure()?.errorText}));const r=await p.goto(url,{waitUntil:'domcontentloaded',timeout:90000});check((mobile?'Mobile':'Desktop')+' HTTPS page responds 200',r.status()===200);await p.waitForTimeout(1500);if(!await p.locator('#world').count()){const choices=p.getByRole('button',{name:/continue|proceed|confirm|open|yes|view/i});if(await choices.count())await choices.first().click();else{const links=p.getByRole('link',{name:/continue|proceed|confirm|open|yes|view/i});if(await links.count())await links.first().click();}}await ready(p);return{p,c};}
(async()=>{let browser,p,context,failure=null,desktopStatus,mobileStatus;
try{
 browser=await chromium.launch({headless:false,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
 ({p,c:context}=await open(browser));desktopStatus=await visual(p);
 check('Actual public HTTPS origin and native storage',await p.evaluate("location.origin==='https://rawcdn.githack.com' && typeof window.__storageMock==='undefined'"));
 check('Actual OSM geometry, no schematic fallback',desktopStatus.mapMode==='osm'&&desktopStatus.roads===7562&&desktopStatus.buildings===10617&&desktopStatus.coast==='OSM',desktopStatus);
 check('Six self-hosted photo textures loaded',desktopStatus.photoTexturesLoaded===6&&desktopStatus.photoTextureErrors.length===0);
 check('Unverified facades and photography state truthful',!desktopStatus.streetViewPhotography&&!desktopStatus.satelliteImagery&&!desktopStatus.facadesSurveyed&&(await p.locator('#data-status').innerText()).includes('외관'));
 await p.screenshot({path:'realism-qa/desktop-day.png'});
 await p.locator('[data-light=golden]').click();check('Golden-hour lighting changes', (await visual(p)).preset==='golden');await p.waitForTimeout(400);await p.screenshot({path:'realism-qa/desktop-golden.png'});
 await p.locator('[data-light=blue]').click();check('Blue-hour lighting changes',(await visual(p)).preset==='blue');await p.waitForTimeout(400);await p.screenshot({path:'realism-qa/desktop-blue.png'});
 await p.locator('[data-light=day]').click();await p.locator('#real-quality').click();check('Light rendering mode disables shadows',!(await visual(p)).shadows);await p.locator('#real-quality').click();check('High-quality shadow mode restored',(await visual(p)).shadows);
 await p.locator('#real-cinema').click();check('Cinematic mode hides sidebar',!(await p.locator('#sidebar').isVisible()));await p.locator('#real-cinema').click();
 check('Existing 32 curated place records retained',(await state(p)).places===32);
 await p.locator('#filters [data-category=hotel]').click();check('Seven hotel records retained',await p.locator('.place-card').count()===7);await p.locator('#search').fill('휘슬락');check('Hotel search',await p.locator('.place-card').count()===1);await p.locator('.place-title').click();check('Information popup opens',await p.locator('#detail').isVisible());
 check('Official Naver search link retained',(await p.locator('.naver-link').getAttribute('href')).startsWith('https://map.naver.com/p/search/'));await p.screenshot({path:'realism-qa/popup.png'});await p.locator('#detail-save').click();await p.locator('.detail-close').click();
 await p.locator('#avatar-open').click();await p.locator('#character-name').fill('제주 미리걷기');await p.locator('#swatches button').nth(2).click();await p.locator('#avatar-save').click();await p.reload({waitUntil:'domcontentloaded'});await ready(p);
 check('Character persists in real HTTPS storage',(await p.locator('#avatar-name-label').innerText()).includes('제주 미리걷기'));check('Itinerary persists on reload',(await state(p)).saved.includes('whistle'));
 await p.locator('#walk-mode').click();const a=(await state(p)).position;await p.keyboard.down('KeyD');await p.waitForTimeout(1200);await p.keyboard.up('KeyD');const b=(await state(p)).position;check('Keyboard moves character along the real-road graph',Math.hypot(a[0]-b[0],a[1]-b[1])>.1);await p.screenshot({path:'realism-qa/walk-day.png'});
 await p.locator('[data-light=golden]').click();await p.waitForTimeout(500);await p.screenshot({path:'realism-qa/walk-golden.png'});
 await p.locator('.topnav [data-tab=tours]').click();check('Three theme walk definitions retained',await p.locator('.tour-card').count()===3);let started=false;for(let i=0;i<3&&!started;i++){await p.locator('.tour-card button').nth(i).click();await p.waitForTimeout(500);started=(await state(p)).auto;}check('At least one curated walk routes on actual OSM graph',started);const distance=(await state(p)).distance;await p.waitForTimeout(800);check('Automatic route progresses',(await state(p)).distance>distance);await p.keyboard.press('ArrowRight');check('Manual input interrupts automatic walk',!(await state(p)).auto);
 await context.close();({p,c:context}=await open(browser,true));mobileStatus=await visual(p);check('Mobile uses light default quality',mobileStatus.quality==='light'&&!mobileStatus.shadows);check('Mobile no horizontal overflow',await p.evaluate('document.documentElement.scrollWidth<=innerWidth'));await p.screenshot({path:'realism-qa/mobile-overview.png'});
 await p.locator('#mobile-places').click();await p.locator('#search').fill('관덕정');await p.locator('.place-title').first().click();check('Mobile place popup',await p.locator('#detail').isVisible());await p.locator('#start-here').click();check('Mobile walking mode starts',(await state(p)).mode==='walk');
 const box=await p.locator('#joystick').boundingBox(),before=(await state(p)).position;await p.mouse.move(box.x+box.width/2+23,box.y+box.height/2);await p.mouse.down();await p.waitForTimeout(1300);await p.mouse.up();const after=(await state(p)).position;check('Mobile joystick moves avatar',Math.hypot(before[0]-after[0],before[1]-after[1])>.1);await p.screenshot({path:'realism-qa/mobile-walk.png'});
 await p.locator('[data-light=golden]').click();check('Mobile lighting control remains usable',(await visual(p)).preset==='golden');await context.close();check('No JavaScript or WebGL shader errors',errors.length===0,errors);
}catch(e){failure=String(e);console.error(failure);try{await p?.screenshot({path:'realism-qa/failure.png',timeout:10000});console.log((await p?.locator('body').innerText())?.slice(0,1600));}catch{}}
finally{if(browser)await browser.close();}
const report={url,testedAt:new Date().toISOString(),runId:process.env.GITHUB_RUN_ID,ok:!failure,passed:checks.filter(c=>c.passed).length,checks,errors,failedRequests,failure,desktopStatus,mobileStatus,scope:'Real HTTPS origin in desktop/mobile-sized Chromium with software WebGL2. Not a real-device benchmark, surveying, Naver validation, or street photography.'};
fs.writeFileSync('realism/browser-result.json',JSON.stringify(report,null,2));fs.writeFileSync('realism-qa/results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(!report.ok)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
